version: 2.1

orbs:
  composer: itinerisltd/composer@0

workflows:
  test:
    jobs:
      - composer/install:
          name: style-check-php-latest
          post-steps:
            - composer/exec:
                command: style:check

      - composer/install:
          name: style-check-php-72
          executor: composer/seven_two
          post-steps:
            - composer/exec:
                command: style:check

      - composer/install:
          name: phpstan-analyse
          post-steps:
            - composer/exec:
                command: phpstan:analyse
